/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atmel_inscreenproximitydemo_TestJni */

#ifndef _Included_com_atmel_inscreenproximitydemo_TestJni
#define _Included_com_atmel_inscreenproximitydemo_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atmel_inscreenproximitydemo_TestJni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atmel_inscreenproximitydemo_TestJni_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_atmel_inscreenproximitydemo_TestJni
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atmel_inscreenproximitydemo_TestJni_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
